package com.yihukurama.mvc4a.model.access.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long index;
    /** Not-null value. */
    private String AICHAID;
    private String MOBILE;
    private String HEAD_URL;
    private String NICKNAME;
    private String EMAIL;
    private String QRCODE;
    private String SEX;
    private String ZONE;
    private String SIGN;

    public User() {
    }

    public User(Long index) {
        this.index = index;
    }

    public User(Long index, String AICHAID, String MOBILE, String HEAD_URL, String NICKNAME, String EMAIL, String QRCODE, String SEX, String ZONE, String SIGN) {
        this.index = index;
        this.AICHAID = AICHAID;
        this.MOBILE = MOBILE;
        this.HEAD_URL = HEAD_URL;
        this.NICKNAME = NICKNAME;
        this.EMAIL = EMAIL;
        this.QRCODE = QRCODE;
        this.SEX = SEX;
        this.ZONE = ZONE;
        this.SIGN = SIGN;
    }

    public Long getIndex() {
        return index;
    }

    public void setIndex(Long index) {
        this.index = index;
    }

    /** Not-null value. */
    public String getAICHAID() {
        return AICHAID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAICHAID(String AICHAID) {
        this.AICHAID = AICHAID;
    }

    public String getMOBILE() {
        return MOBILE;
    }

    public void setMOBILE(String MOBILE) {
        this.MOBILE = MOBILE;
    }

    public String getHEAD_URL() {
        return HEAD_URL;
    }

    public void setHEAD_URL(String HEAD_URL) {
        this.HEAD_URL = HEAD_URL;
    }

    public String getNICKNAME() {
        return NICKNAME;
    }

    public void setNICKNAME(String NICKNAME) {
        this.NICKNAME = NICKNAME;
    }

    public String getEMAIL() {
        return EMAIL;
    }

    public void setEMAIL(String EMAIL) {
        this.EMAIL = EMAIL;
    }

    public String getQRCODE() {
        return QRCODE;
    }

    public void setQRCODE(String QRCODE) {
        this.QRCODE = QRCODE;
    }

    public String getSEX() {
        return SEX;
    }

    public void setSEX(String SEX) {
        this.SEX = SEX;
    }

    public String getZONE() {
        return ZONE;
    }

    public void setZONE(String ZONE) {
        this.ZONE = ZONE;
    }

    public String getSIGN() {
        return SIGN;
    }

    public void setSIGN(String SIGN) {
        this.SIGN = SIGN;
    }

}
